language: cpp
compiler:
    - clang
    - gcc
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - cmake
script:
    - mkdir build
    - cd build
    - cmake ..
    - cmake --build .
